/***********************************************************************/
/*                                                                     */
/*  FILE        :TestAX5043.c                                          */
/*  DATE        :Mon, Dec 09, 2013                                     */
/*  DESCRIPTION :main program file.                                    */
/*  CPU GROUP   :10                                                    */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.18).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/
//#include "sfr_r81B.h"
#ifndef _RADIO_H_
#define _RADIO_H_

#include "rtthread.h"

#define CHANNEL_NUM	1
extern uint8_t ubReceiveFlag;

void SpiPowerDown(void);
void AX5043_OFF(void);
void Receive_ISR(void *parameter);
void SpiWriteByte(uint8_t ubByte);
void SpiWriteWord(uint16_t ubByte);
uint8_t SpiReadByte(void);
void SpiWriteSingleAddressRegister(uint8_t Addr, uint8_t Data);
void SpiWriteLongAddressRegister(uint16_t Addr, uint8_t Data);
uint8_t SpiReadSingleAddressRegister(uint8_t Addr);
uint8_t SpiReadLongAddressRegister(uint16_t Addr);
void RF_CommonPWRMODE(uint8_t ubCom);
void InitAx5043REG(void);
void AX5043_Reset(void);
uint8_t InitAX5043(void);
void ChangeWorFreq(void);
void BackNormalFreq(void);
void ChangeMaxPower(void);
void BackNormalPower(void);


void RdioWaitXtal(void);
char SetChannel(uint8_t ubNum );

void SetTransmitMode(void);
void transmit_packet(void);
void ReceiveData(void);
void enable_wor(void);
void AX5043ReceiverON(void);
void SetReceiveMode(void);
void RdioXtalON(void);
void Ax5043SetRegisters_RX(void);
void IRQ_Bounding(void);
void Radio_Task_Init(void);
void WirelessBitRate_20K(void);
void transmit_packet_task(uint8_t *Buf, uint8_t u8Len);
void Normal_send(uint8_t *Buf, uint8_t u8Len);
void Wor_send(uint8_t *Buf, uint8_t u8Len);
#endif

/*************************the end of file*******************************/
